model_name: "stabilityai/sdxl-turbo"
data_dir: "./scribble_tune/data/quickdraw_512"
output_dir: "./finetune_scribble/output"
resolution: 512
learning_rate: 1.0e-6
lr_scheduler: "cosine"
train_batch_size: 16
gradient_accumulation_steps: 1
num_epochs: 3
mixed_precision: "fp16"
checkpointing_steps: 1000
max_grad_norm: 1.0
seed: 42
wandb_project: "scribble_finetune"
wandb_entity: "conditional-matching"
