"""LM-on-LM conditional distribution matching with an EXACT oracle.

Task: find a framing x (a short preamble, generated by a masked diffusion LM)
such that a responder LM's answer distribution on a fixed multiple-choice
survey question matches a target population distribution G.

Why this task exists. In the image pipeline p(y|x) is only accessible through
Monte Carlo (sample images, CLIP-embed, biased MMD), so every loss value
carries estimator noise and there is a finite-sample floor. Here the
responder's answer is restricted to a small fixed option set, so

    p(y = option_j | x) = softmax(logits at the answer position)[j],
    renormalised over the option tokens,

is available EXACTLY from one forward pass. Consequences:
  * the optimum is a true zero, not a finite-sample floor;
  * L(x) is deterministic, so the only remaining stochasticity in guided
    sampling is the TWIST estimate itself -- which is exactly the mechanism
    the CTMC-vs-SMC comparison is about;
  * an eval costs milliseconds, so the whole prompt space can be enumerated
    by brute force at small vocabulary and every method scored against the
    true optimum rather than against the best value anyone happened to find.

The controlled vocabulary (--vocab_words / --vocab) makes |V| the single free
variable for the V-ladder: the framing words are nominally about *how* the
question is asked, never about the answer itself, so the answer distribution
stays underdetermined by construction.
"""

import argparse
import itertools
import json
import os
import sys
import time

import numpy as np
import torch

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from ctmc_guidance import fit_additive_theta  # noqa: E402
from real_ctmc import ctmc_chain, fit_theta_anova  # noqa: E402
from real_smc import MASK, BertMaskedPrior, run_smc  # noqa: E402

LETTERS = ["A", "B", "C", "D", "E", "F", "G"]

# Framing words, all single bert-base-uncased tokens. Deliberately about the
# ASKING (audience, tone, instruction), never about the answer options.
_LADDER = ["please", "honestly", "carefully", "consider", "imagine",
           "typical", "average", "random", "american", "adults",
           "people", "survey", "asked", "answer", "opinion", "diverse",
           "different", "views", "many", "most", "few", "mixed",
           "balanced", "national", "poll", "population", "voters",
           "citizens", "young", "older", "religious", "rural"]

# The V-ladder rungs are strict PREFIXES of one another, so growing V only
# adds prompts: the optimum is monotonically non-increasing in V and the task
# semantics never change. |V| is then the single free variable when comparing
# search methods across rungs.
VOCAB_SETS = {
    "tiny": ["please", "honestly", "typical", "american"],
    "small": ["please", "honestly", "carefully", "typical", "average",
              "american", "adults", "survey"],
    "medium": list(_LADDER),
    "v4": _LADDER[:4], "v8": _LADDER[:8], "v16": _LADDER[:16],
    "v32": _LADDER[:32],
}

# Answer-distribution targets.
#
# SOURCING RULE: entries whose key starts with "synthetic_" are invented by us
# and exist only to exercise the machinery (mechanism experiments, V-ladder,
# brute force). Entries carrying a "source" URL are real published marginals
# and must never be edited by hand without re-checking the source.
PEW_W183 = (
    "Pew Research Center American Trends Panel Wave 183 (Political Typology), "
    "fielded Nov 17-30 2025, N=10,357 US adults. Topline: "
    "https://www.pewresearch.org/wp-content/uploads/sites/20/2026/06/"
    "PP_2026.5.10_political-typology_topline.pdf"
)
PEW_W185 = (
    "Pew Research Center American Trends Panel Wave 185 (Politics January), "
    "fielded Jan 20-26 2026, N=8,512 US adults. Topline: "
    "https://www.pewresearch.org/wp-content/uploads/sites/20/2026/03/"
    "PP_3.12.2026_abortion_topline.pdf"
)
QUESTIONS = {
    "synthetic_split": {
        "question": ("Do you think the government should increase spending "
                     "on public transportation?"),
        "options": ["Yes", "No"],
        "target": [0.5, 0.5],
        "source": "SYNTHETIC - invented 50/50 target, not survey data",
    },
    "synthetic_polarized": {
        "question": ("How would you describe your view of the current "
                     "economic situation in your country?"),
        "options": ["Very good", "Somewhat good", "Neutral",
                    "Somewhat bad", "Very bad"],
        "target": [0.30, 0.10, 0.08, 0.12, 0.40],
        "source": "SYNTHETIC - invented U-shaped/polarized target",
    },
    "synthetic_skewed": {
        "question": "Is it important to you that elections are fair?",
        "options": ["Very important", "Somewhat important",
                    "Not too important", "Not at all important"],
        "target": [0.80, 0.14, 0.04, 0.02],
        "source": "SYNTHETIC - invented skewed target for contrast",
    },
    # ---- real published marginals -------------------------------------
    # Targets are the published percentages of the substantive options,
    # verbatim from the topline PDFs; the "No answer" residual (1-3%) is
    # dropped because the responder cannot express it, and SurveyAnswerLoss
    # renormalises. Percentages are stored raw so they stay checkable against
    # the source. Pew rows sometimes sum to 99/101 from rounding.
    "pew_govsize": {  # near 50/50
        "question": ("If you had to choose, would you rather have a smaller "
                     "government providing fewer services, or a bigger "
                     "government providing more services?"),
        "options": ["A smaller government providing fewer services",
                    "A bigger government providing more services"],
        "target": [46, 53],
        "source": PEW_W183 + " | GOVSIZE1 | No answer 2% dropped",
    },
    "pew_econ_fairness": {
        "question": ("Overall, would you say the economic system in this "
                     "country is..."),
        "options": ["Extremely fair", "Very fair", "Somewhat fair",
                    "Not too fair", "Not at all fair"],
        "target": [2, 11, 35, 31, 19],
        "source": PEW_W183 + " | ECON_FAIRNESS | No answer 1% dropped",
    },
    "pew_legal_immig": {
        "question": ("Do you think the number of legal immigrants the U.S. "
                     "admits should..."),
        "options": ["Increase a lot", "Increase a little",
                    "Stay about the same", "Decrease a little",
                    "Decrease a lot"],
        "target": [11, 18, 45, 12, 13],
        "source": PEW_W183 + " | LEGALIMMIGAMT | No answer 1% dropped",
    },
    "pew_crim_sent": {  # two near-tied modes
        "question": ("Overall, would you say people who are convicted of "
                     "crimes in this country serve..."),
        "options": ["Too much time in prison", "Too little time in prison",
                    "About the right amount of time"],
        "target": [17, 41, 40],
        "source": PEW_W183 + " | CRIM_SENT2 | No answer 3% dropped",
    },
    "pew_polfut": {
        "question": ("How much confidence do you have in the future of the "
                     "U.S. political system?"),
        "options": ["A lot", "Some", "Not too much", "None at all"],
        "target": [7, 37, 42, 13],
        "source": PEW_W183 + " | POLFUT | No answer 1% dropped",
    },
    "pew_just_error": {  # skewed, for contrast
        "question": ("No system of justice is perfect, but which do you "
                     "think would be worse?"),
        "options": ["Convicting an innocent person",
                    "Letting a guilty person go free"],
        "target": [73, 26],
        "source": PEW_W183 + " | JUST_ERROR | No answer 1% dropped",
    },
    "pew_abortion": {
        "question": "Do you think abortion should be...",
        "options": ["Legal in all cases", "Legal in most cases",
                    "Illegal in most cases", "Illegal in all cases"],
        "target": [23, 37, 28, 11],
        "source": PEW_W185 + " | ABRTLGL | No answer 2% dropped",
    },
    "pew_conception": {  # U-SHAPED: mass at both extremes, dip in the middle
        "question": ("Regardless of whether you think abortion should be "
                     "legal or illegal, how well does the following "
                     "statement describe your views? \"Human life begins at "
                     "conception, so an embryo is a person with rights\""),
        "options": ["Extremely well", "Very well", "Somewhat well",
                    "Not too well", "Not at all well"],
        "target": [28, 11, 17, 19, 24],
        "source": (PEW_W185 + " | ABRTVIEW item c, Form 1 N=4,250 | "
                   "No answer 1% dropped"),
    },
    "pew_woman_decides": {
        "question": ("Regardless of whether you think abortion should be "
                     "legal or illegal, how well does the following "
                     "statement describe your views? \"The decision about "
                     "whether to have an abortion should belong solely to "
                     "the pregnant woman\""),
        "options": ["Extremely well", "Very well", "Somewhat well",
                    "Not too well", "Not at all well"],
        "target": [33, 19, 20, 13, 14],
        "source": (PEW_W185 + " | ABRTVIEW item a, Form 1 N=4,250 | "
                   "No answer 1% dropped"),
    },
}


class SurveyAnswerLoss:
    """Exact categorical oracle: L(framing) = distance(p(answer|framing), G).

    One forward pass per unique framing, softmax restricted to the option
    letters. Caches by text and counts unique evaluations, matching the
    loss_fn interface the SMC/CTMC code expects (callable + .n_evals)."""

    def __init__(self, question, options, target, responder, device,
                 metric="tv", dtype=None):
        from transformers import AutoModelForCausalLM, AutoTokenizer

        self.tok = AutoTokenizer.from_pretrained(responder)
        kw = {} if dtype is None else {"dtype": dtype}
        self.model = (AutoModelForCausalLM.from_pretrained(responder, **kw)
                      .to(device).eval())
        self.device = device
        self.question = question
        self.options = options
        self.letters = LETTERS[:len(options)]
        g = np.asarray(target, dtype=np.float64)
        assert len(g) == len(options), "target/options length mismatch"
        self.G = g / g.sum()
        self.metric = metric
        self.chat = getattr(self.tok, "chat_template", None) is not None
        # first-token id of each option letter as it appears at the answer
        # position: bare "A" after a chat generation prompt, " A" after "Answer:"
        self.opt_ids = [
            self.tok(L if self.chat else f" {L}",
                     add_special_tokens=False)["input_ids"][0]
            for L in self.letters
        ]
        assert len(set(self.opt_ids)) == len(self.opt_ids), \
            "option letters collide in the responder tokenizer"
        self.cache = {}
        self.dist_cache = {}
        self.n_evals = 0

    def _build(self, framing):
        opts = "\n".join(f"{L}. {o}"
                         for L, o in zip(self.letters, self.options))
        body = (f"{framing.strip()}\n\n{self.question}\n{opts}\n\n"
                "Answer with a single letter.")
        if self.chat:
            return self.tok.apply_chat_template(
                [{"role": "user", "content": body}],
                tokenize=False, add_generation_prompt=True)
        return body + "\nAnswer:"

    @torch.no_grad()
    def answer_dist(self, framing):
        """Exact p(option | framing) -- one forward pass, no sampling."""
        if framing in self.dist_cache:
            return self.dist_cache[framing]
        ids = self.tok(self._build(framing), return_tensors="pt",
                       add_special_tokens=not self.chat).to(self.device)
        logits = self.model(**ids).logits[0, -1].float()
        sub = logits[self.opt_ids]
        p = torch.softmax(sub, dim=-1).cpu().numpy().astype(np.float64)
        p = p / p.sum()
        self.dist_cache[framing] = p
        return p

    def distance(self, p):
        if self.metric == "tv":
            return 0.5 * float(np.abs(p - self.G).sum())
        if self.metric == "kl":  # KL(G || p), finite since p > 0
            return float((self.G * np.log(self.G / np.maximum(p, 1e-12))).sum())
        if self.metric == "l2":
            return float(np.linalg.norm(p - self.G))
        if self.metric == "hellinger":
            return float(np.linalg.norm(np.sqrt(p) - np.sqrt(self.G))
                         / np.sqrt(2.0))
        raise ValueError(self.metric)

    def __call__(self, text):
        if text not in self.cache:
            self.cache[text] = self.distance(self.answer_dist(text))
            self.n_evals += 1
        return self.cache[text]

    def fork(self):
        """Fresh loss cache and eval counter, sharing the model and the
        (deterministic) answer-distribution cache. Each method must be
        charged for its own oracle calls, or whichever arm runs first makes
        the later ones look free -- but re-running the forward pass for a
        framing we have already scored would only waste time, since the
        oracle is exact and therefore identical across methods."""
        import copy

        other = copy.copy(self)
        other.cache = {}
        other.n_evals = 0
        return other

    def best_seen(self):
        """(L, text) over every framing evaluated so far -- the cache is the
        method's full search trace, so this is a budget-matched 'best found'
        comparable across methods."""
        t = min(self.cache, key=self.cache.get)
        return self.cache[t], t

    def report(self, framing):
        p = self.answer_dist(framing)
        return {"framing": framing, "L": self.distance(p),
                "p": [round(float(v), 4) for v in p]}


def resolve_vocab(words, tok_name="bert-base-uncased"):
    """Keep only words that are single tokens of the prior's tokenizer."""
    from transformers import AutoTokenizer

    tok = AutoTokenizer.from_pretrained(tok_name)
    vocab = tok.get_vocab()
    kept = [w for w in words if w in vocab]
    dropped = [w for w in words if w not in vocab]
    if dropped:
        print(f"[vocab] dropped {len(dropped)} non-single-token words: "
              f"{dropped}", flush=True)
    return kept


def brute_force(prior, loss_fn, max_evals):
    """Exact optimum over the whole controlled-vocabulary prompt space."""
    total = prior.A ** prior.canvas_len
    if total > max_evals:
        return {"skipped": True, "space_size": total,
                "reason": f"space {total} > --brute_max {max_evals}"}
    t0 = time.perf_counter()
    best_l, best_x = np.inf, None
    dists = []
    for combo in itertools.product(range(prior.A),
                                  repeat=prior.canvas_len):
        x = np.array(combo, dtype=int)
        text = prior.decode(x)
        l = loss_fn(text)
        dists.append(loss_fn.answer_dist(text))
        if l < best_l:
            best_l, best_x = l, x
    # Reachability of the target: how much spread can ANY framing induce?
    # A responder that collapses to one-hot has max_entropy ~ 0 and cannot
    # match a spread target no matter how well the prompt space is searched,
    # which is a property of the responder, not of the search method.
    D = np.array(dists)
    ent = -(D * np.log(np.maximum(D, 1e-12))).sum(axis=1)
    g = loss_fn.G
    return {"skipped": False, "space_size": total, "L_opt": float(best_l),
            "x_opt_decode": prior.decode(best_x),
            "dist_opt": loss_fn.report(prior.decode(best_x))["p"],
            "entropy_target": float(
                -(g * np.log(np.maximum(g, 1e-12))).sum()),
            "entropy_max": float(ent.max()),
            "entropy_mean": float(ent.mean()),
            "frac_near_onehot": float((D.max(axis=1) > 0.95).mean()),
            "reach_min": [round(float(v), 4) for v in D.min(axis=0)],
            "reach_max": [round(float(v), 4) for v in D.max(axis=0)],
            "wall_clock_s": time.perf_counter() - t0}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--question", default="synthetic_split",
                    choices=sorted(QUESTIONS))
    ap.add_argument("--responder", default="Qwen/Qwen2.5-1.5B-Instruct")
    ap.add_argument("--metric", default="tv",
                    choices=["tv", "kl", "l2", "hellinger"])
    ap.add_argument("--vocab", default="small", choices=sorted(VOCAB_SETS))
    ap.add_argument("--vocab_words", default=None,
                    help="comma-separated override of the controlled vocab")
    ap.add_argument("--canvas_len", type=int, default=3)
    ap.add_argument("--methods", default="probe,brute,unguided,smc,ctmc")
    ap.add_argument("--seeds", type=int, nargs="+", default=[0])
    ap.add_argument("--beta", type=float, default=200.0)
    ap.add_argument("--no_anneal", action="store_true")
    # SMC
    ap.add_argument("--N", type=int, default=128)
    ap.add_argument("--T", type=int, default=16)
    ap.add_argument("--estimator", default="mode",
                    choices=["mode", "sampled"])
    ap.add_argument("--n_dec", type=int, default=8)
    ap.add_argument("--remask_sigma", type=float, default=0.0)
    # CTMC
    ap.add_argument("--gamma", type=float, default=10.0)
    ap.add_argument("--K", type=int, default=16)
    ap.add_argument("--restarts", type=int, default=4)
    ap.add_argument("--eta", type=float, default=0.0)
    ap.add_argument("--remask_guided", action="store_true")
    ap.add_argument("--ctmc_estimator", default="mc",
                    choices=["mc", "additive", "unguided"])
    ap.add_argument("--n_steps", type=int, default=16)
    # unguided baseline budget
    ap.add_argument("--B", type=int, default=256)
    ap.add_argument("--brute_max", type=int, default=200_000)
    ap.add_argument("--probe_framings", default=None,
                    help="';'-separated framings for the probe arm")
    ap.add_argument("--outdir", default="output/lm_survey")
    args = ap.parse_args()

    device = ("mps" if torch.backends.mps.is_available()
              else "cuda" if torch.cuda.is_available() else "cpu")
    os.makedirs(args.outdir, exist_ok=True)
    spec = QUESTIONS[args.question]
    words = (args.vocab_words.split(",") if args.vocab_words
             else VOCAB_SETS[args.vocab])
    words = resolve_vocab(words)

    print(f"device={device} question={args.question} metric={args.metric}")
    print(f"target G={spec['target']} source={spec['source']}")

    loss_fn = SurveyAnswerLoss(spec["question"], spec["options"],
                               spec["target"], args.responder, device,
                               metric=args.metric)
    prior = BertMaskedPrior("bert-base-uncased", device, "", args.canvas_len,
                            vocab_words=words)
    print(f"prior: canvas_len={prior.canvas_len} |V|={prior.A} "
          f"space={prior.A ** prior.canvas_len}", flush=True)

    # sanity anchors: the empty framing, and the target itself
    empty = loss_fn.report("")
    print(f"[anchor] empty framing L={empty['L']:.4f} p={empty['p']}",
          flush=True)

    out = {"config": vars(args), "device": device, "question_spec": spec,
           "vocab": words, "canvas_len": prior.canvas_len, "V": int(prior.A),
           "anchor_empty": empty, "runs": []}
    methods = args.methods.split(",")
    anneal = not args.no_anneal

    if "probe" in methods:
        framings = (args.probe_framings.split(";") if args.probe_framings
                    else ["", "please answer honestly",
                          "imagine a nationally representative sample "
                          "of american adults",
                          "you are a conservative religious voter",
                          "you are a young progressive city dweller",
                          "answer as the average person would",
                          "opinions on this are deeply divided"])
        probe = [loss_fn.report(f) for f in framings]
        for r in sorted(probe, key=lambda r: r["L"]):
            print(f"[probe] L={r['L']:.4f} p={r['p']} '{r['framing']}'",
                  flush=True)
        out["probe"] = probe

    if "brute" in methods:
        lf = loss_fn.fork()
        bf = brute_force(prior, lf, args.brute_max)
        bf["unique_evals"] = lf.n_evals
        print(f"[brute] {json.dumps(bf)}", flush=True)
        out["brute"] = bf

    all_masked = np.full(prior.canvas_len, MASK, dtype=int)

    for seed in args.seeds:
        # Guided arms run first so the unguided baseline can be given exactly
        # their oracle budget: an unguided arm that draws more unique prompts
        # than the guided ones is not a baseline, it is a bigger search.
        guided_evals = []

        if "smc" in methods:
            lf = loss_fn.fork()
            res, _ = run_smc(prior, lf, args.estimator, args.N, args.T,
                             args.beta, args.n_dec, seed, beta_anneal=anneal,
                             verbose=False,
                             remask_sigma=args.remask_sigma)
            l_seen, t_seen = lf.best_seen()
            rec = {"method": "smc", "seed": seed,
                   "L_best": res["L_best"],
                   "text_best": res["x_best_decode"],
                   "dist_best": loss_fn.report(res["x_best_decode"])["p"],
                   "L_best_seen": l_seen, "text_best_seen": t_seen,
                   "unique_evals": lf.n_evals,
                   "wall_clock_s": res["wall_clock_s"],
                   "n_resamples": res["n_resamples"]}
            print(f"[smc s{seed}] L={rec['L_best']:.4f} "
                  f"'{rec['text_best']}' evals={rec['unique_evals']}",
                  flush=True)
            guided_evals.append(lf.n_evals)
            out["runs"].append(rec)

        if "ctmc" in methods:
            lf = loss_fn.fork()
            theta = None
            if args.ctmc_estimator == "additive":
                rng_th = np.random.default_rng(800_000 + seed)
                Xd, Ld = [], []
                for _ in range(256):
                    x = ctmc_chain(prior, lf, rng_th, args.n_steps,
                                   args.beta, 0.0, "unguided", 1, None,
                                   all_masked, 1.0, anneal, 0)
                    Xd.append(x)
                    Ld.append(lf(prior.decode(x)))
                theta = fit_theta_anova(prior.canvas_len, prior.A,
                                        np.array(Xd), np.array(Ld),
                                        args.beta)
            t0 = time.perf_counter()
            rng = np.random.default_rng(900_000 + seed)
            best = (np.inf, None)
            for _ in range(args.restarts):
                x = ctmc_chain(prior, lf, rng, args.n_steps, args.beta,
                               args.gamma, args.ctmc_estimator, args.K,
                               theta, all_masked, 1.0, anneal, 0,
                               eta=args.eta,
                               remask_guided=args.remask_guided)
                text = prior.decode(x)
                l = lf(text)
                if l < best[0]:
                    best = (l, text)
            rec = {"method": f"ctmc_{args.ctmc_estimator}", "seed": seed,
                   "gamma": args.gamma, "K": args.K, "eta": args.eta,
                   "remask_guided": args.remask_guided,
                   "L_best": best[0], "text_best": best[1],
                   "dist_best": loss_fn.report(best[1])["p"],
                   "unique_evals": lf.n_evals,
                   "wall_clock_s": time.perf_counter() - t0}
            print(f"[{rec['method']} s{seed}] L={rec['L_best']:.4f} "
                  f"'{rec['text_best']}' evals={rec['unique_evals']}",
                  flush=True)
            guided_evals.append(lf.n_evals)
            out["runs"].append(rec)

        if "unguided" in methods:
            # budget = the largest guided arm's unique-eval count, so the
            # baseline is matched rather than merely "256 draws"
            budget = max(guided_evals) if guided_evals else args.B
            rng = np.random.default_rng(700_000 + seed)
            lf = loss_fn.fork()
            t0 = time.perf_counter()
            best, draws = (np.inf, None), 0
            while lf.n_evals < budget and draws < 100 * budget:
                x = ctmc_chain(prior, lf, rng, args.n_steps, args.beta,
                               0.0, "unguided", 1, None, all_masked, 1.0,
                               anneal, 0)
                text = prior.decode(x)
                l = lf(text)
                draws += 1
                if l < best[0]:
                    best = (l, text)
            rec = {"method": "unguided", "seed": seed, "L_best": best[0],
                   "text_best": best[1],
                   "dist_best": loss_fn.report(best[1])["p"],
                   "unique_evals": lf.n_evals, "budget": budget,
                   "draws": draws,
                   "wall_clock_s": time.perf_counter() - t0}
            print(f"[unguided s{seed}] L={rec['L_best']:.4f} "
                  f"'{rec['text_best']}' evals={rec['unique_evals']}"
                  f"/{budget}", flush=True)
            out["runs"].append(rec)

    path = os.path.join(args.outdir, "metrics.json")
    with open(path, "w") as f:
        json.dump(out, f, indent=1)
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
